version: '3.9'
services:
  mysql:
    image: mysql:latest
    container_name: sujay_sql_contanier7
    environment:
      MYSQL_DATABASE: sales_db  
      MYSQL_USER: root 
      MYSQL_PASSWORD: 12345678
    ports:
      - "3306:3306"
    networks:
      - ola_network


  springboot:
    build: .
    container_name: sales_history_app
    ports:
      - "8978:8978"
    depends_on:
      - mysql
    networks:
      - ola_network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database-1.cmdlxfdnrfju.ap-south-1.rds.amazonaws.com:3306/sales_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345678

networks:
  ola_network:
    driver: bridge
